### Obtain Access and Refresh Token
POST http://localhost:8080/authentication/login
Content-Type: application/json

{
  "email": "anthony@eno-intern.de",
  "password": "test"
}

### Renew Access Token
GET http://localhost:8080/authentication/refresh
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIyMGQyYmM0MS1kZWI5LTQ5MTgtOTdlMy02MzU3MDE0ZWEyN2YiLCJpYXQiOjE3NTk4MTc1NTksImV4cCI6MTc1OTgyMTE1OSwic2NwIjoiQURNSU5JU1RSQVRPUiIsInR5cGUiOiJyZWZyZXNoX3Rva2VuIn0.Wx-739F7HDEJjpiyLtrAtO0ygNwI-oUhL2D60wyMuScGLJUrVr3Hpdw0T_fnTPOH