### GET request to example server
GET http://localhost:8080/jobs/qualifications?limit=10&offset=0
Authorization: Bearer {{ACCESS_TOKEN}}

### GET specific qualification
GET http://localhost:8080/jobs/qualifications/554624b0-22b5-4a79-aabf-5981d3dd0fdc
Authorization: Bearer {{ACCESS_TOKEN}}

### Create Qualification
POST http://localhost:8080/jobs/qualifications
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "name": "test231",
  "description": "test desc",
  "minimumDuration": 1
}